import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Mail, Phone, MapPin, ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';
export default function Contact() {
    const contacts = [
        { icon: Mail, label: 'Email', value: 'info@trfc.ke', href: 'mailto:info@trfc.ke' },
        { icon: Phone, label: 'Phone', value: '+254 712 345 678', href: 'tel:+254712345678' },
        { icon: MapPin, label: 'Location', value: 'Thika Road, Nairobi, Kenya', href: 'https://maps.google.com/?q=Thika+Road+Nairobi' },
    ];
    return (_jsxs("div", { className: "min-h-screen bg-night text-chalk font-barlow", children: [_jsx("section", { className: "bg-ink border-b border-white/5 px-[6%] pt-14 pb-11", children: _jsxs("div", { className: "max-w-3xl mx-auto", children: [_jsxs("h1", { className: "font-bebas text-5xl", children: ["GET IN ", _jsx("span", { className: "text-fire", children: "TOUCH" })] }), _jsx("p", { className: "text-fog mt-2", children: "Questions about events, membership, or partnerships? We'd love to hear from you." })] }) }), _jsxs("div", { className: "max-w-3xl mx-auto px-[6%] py-10 pb-20", children: [_jsx("div", { className: "space-y-4 mb-12", children: contacts.map(({ icon: Icon, label, value, href }) => (_jsxs("a", { href: href, target: href.startsWith('http') ? '_blank' : undefined, rel: href.startsWith('http') ? 'noopener noreferrer' : undefined, className: "bg-ash border border-white/5 p-6 flex items-center gap-5 no-underline text-chalk hover:border-fire/30 transition group", children: [_jsx("div", { className: "w-12 h-12 bg-fire/10 border border-fire/20 flex items-center justify-center text-fire flex-shrink-0", children: _jsx(Icon, { size: 20 }) }), _jsxs("div", { className: "flex-1", children: [_jsx("p", { className: "font-barlow-condensed font-bold text-xs letter-spacing-widest text-transform-uppercase text-fog", children: label }), _jsx("p", { className: "font-semibold mt-1", children: value })] }), _jsx(ArrowRight, { size: 16, className: "text-fire opacity-0 group-hover:opacity-100 transition" })] }, label))) }), _jsxs("div", { className: "bg-ash border border-white/5 p-8", children: [_jsx("h2", { className: "font-barlow-condensed font-bold text-fire letter-spacing-widest text-transform-uppercase mb-4", children: "Send a Message" }), _jsx("p", { className: "text-fog text-sm mb-6", children: "Prefer email? Tap below to open your mail client with our address pre-filled." }), _jsx("a", { href: "mailto:info@trfc.ke?subject=TRFC%20Enquiry", className: "inline-flex bg-fire text-white px-8 py-3 clip-angled font-barlow-condensed font-black text-sm letter-spacing-widest text-transform-uppercase no-underline hover:bg-ember", children: "Email TRFC" }), _jsxs("p", { className: "text-xs text-fog mt-6", children: ["New to TRFC? ", _jsx(Link, { to: "/register", className: "text-fire no-underline hover:underline", children: "Join the community" }), " or browse ", _jsx(Link, { to: "/events", className: "text-fire no-underline hover:underline", children: "upcoming events" }), "."] })] })] })] }));
}
//# sourceMappingURL=Contact.js.map