import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { ACCESS_COPY } from '../../content/onboarding';
import { StepShell, StepTitle } from './ui';
function TierCard({ name, description, price, button, onClick, highlighted, locked, }) {
    return (_jsxs("div", { className: `flex flex-col p-5 border ${highlighted ? 'border-accent bg-accent/10' : 'border-white/15 bg-white/5'} ${locked ? 'opacity-90' : ''}`, children: [locked && (_jsx("span", { className: "self-start font-barlow-condensed font-bold text-[11px] tracking-widest uppercase text-white/70 border border-white/25 px-2 py-0.5 mb-3", children: ACCESS_COPY.locked.badge })), _jsx("h3", { className: "font-bebas text-3xl leading-none text-white mb-2", children: name }), _jsx("p", { className: "text-sm text-white/85 mb-2", children: description }), price && _jsx("p", { className: "text-xs text-white/60 leading-relaxed mb-4", children: price }), _jsx("button", { type: "button", onClick: onClick, className: `mt-auto font-barlow-condensed font-black text-sm tracking-wider uppercase px-5 py-3 transition-all duration-200 ${highlighted
                    ? 'bg-accent text-black hover:bg-accent/90'
                    : 'border border-white/40 text-white hover:border-accent hover:text-accent'}`, children: button })] }));
}
export default function AccessChoice({ program, onChoose, onSwitchToFoundations, onBack, }) {
    const { elite } = ACCESS_COPY;
    return (_jsxs(StepShell, { eyebrow: program.name, onBack: onBack, children: [_jsx(StepTitle, { children: ACCESS_COPY.title }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-3 mt-6", children: [program.requiresPaid ? (_jsxs(_Fragment, { children: [_jsx(TierCard, { locked: true, name: ACCESS_COPY.locked.free.name, description: ACCESS_COPY.locked.free.description(program.name), button: ACCESS_COPY.locked.free.button, onClick: onSwitchToFoundations }), _jsx(TierCard, { highlighted: true, name: ACCESS_COPY.locked.plus.name(program.name), description: ACCESS_COPY.locked.plus.description, price: ACCESS_COPY.plusPrice, button: ACCESS_COPY.locked.plus.button, onClick: () => onChoose('plus') })] })) : (_jsxs(_Fragment, { children: [_jsx(TierCard, { highlighted: true, name: ACCESS_COPY.foundations.free.name, description: ACCESS_COPY.foundations.free.description, price: ACCESS_COPY.foundations.free.price, button: ACCESS_COPY.foundations.free.button, onClick: () => onChoose('free') }), _jsx(TierCard, { name: ACCESS_COPY.foundations.plus.name, description: ACCESS_COPY.foundations.plus.description, price: ACCESS_COPY.plusPrice, button: ACCESS_COPY.foundations.plus.button, onClick: () => onChoose('plus') })] })), _jsx(TierCard, { name: elite.name, description: elite.description, price: elite.price, button: elite.button, onClick: () => onChoose('elite') })] })] }));
}
//# sourceMappingURL=AccessChoice.js.map