import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Mail, Phone, MapPin } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
export default function Footer() {
    const { user } = useAuth();
    const isAdmin = user && user.role === 'admin';
    return (_jsxs("footer", { className: "bg-dark text-white mt-16", children: [_jsxs("div", { className: "max-w-7xl mx-auto px-4 py-12 grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-8", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-primary font-bold text-lg mb-4", children: "TRFC" }), _jsx("p", { className: "text-gray-300", children: "Thika Road Fitness Community - Building a stronger community together." })] }), _jsxs("div", { children: [_jsx("h4", { className: "font-semibold mb-4", children: "Quick Links" }), _jsxs("ul", { className: "space-y-2 text-gray-300", children: [_jsx("li", { children: _jsx(Link, { to: "/events", className: "hover:text-primary transition", children: "Events" }) }), _jsx("li", { children: _jsx(Link, { to: "/shop", className: "hover:text-primary transition", children: "Shop" }) }), _jsx("li", { children: _jsx("a", { href: "#", className: "hover:text-primary transition", children: "Contact" }) }), _jsx("li", { children: _jsx(Link, { to: "/admin/login", className: "hover:text-primary transition", children: "Admin Login" }) })] })] }), _jsxs("div", { children: [_jsx("h4", { className: "font-semibold mb-4", children: "Contact" }), _jsxs("div", { className: "space-y-2 text-gray-300", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Mail, { size: 18 }), _jsx("span", { children: "info@trfc.ke" })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Phone, { size: 18 }), _jsx("span", { children: "+254 712 345 678" })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(MapPin, { size: 18 }), _jsx("span", { children: "Thika Road, Nairobi" })] })] })] }), isAdmin && (_jsxs("div", { children: [_jsx("h4", { className: "font-semibold mb-4 text-primary", children: "Admin Panel" }), _jsxs("ul", { className: "space-y-2 text-gray-300", children: [_jsx("li", { children: _jsx(Link, { to: "/admin", className: "hover:text-primary transition", children: "Dashboard" }) }), _jsx("li", { children: _jsx(Link, { to: "/admin/events", className: "hover:text-primary transition", children: "Manage Events" }) }), _jsx("li", { children: _jsx(Link, { to: "/admin/products", className: "hover:text-primary transition", children: "Manage Products" }) }), _jsx("li", { children: _jsx(Link, { to: "/admin/gallery", className: "hover:text-primary transition", children: "Manage Gallery" }) }), _jsx("li", { children: _jsx(Link, { to: "/admin/orders", className: "hover:text-primary transition", children: "View Orders" }) }), _jsx("li", { children: _jsx(Link, { to: "/admin/users", className: "hover:text-primary transition", children: "Manage Users" }) })] })] }))] }), _jsx("div", { className: "border-t border-gray-700 py-6 text-center text-gray-400", children: _jsx("p", { children: "\u00A9 2024 TRFC. All rights reserved." }) })] }));
}
//# sourceMappingURL=Footer.js.map